site_name: gumbel_softmax_layer_skipping_2024
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: gumbel_softmax_layer_skipping_2024
      handlers:
        python:
          options:
            docstring_style: numpy